import Head from 'next/head';
import Image from 'next/image';
import { Text } from '@chakra-ui/layout';
import { Box, Center } from '@chakra-ui/layout';
import { FaGithub } from 'react-icons/fa';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
export default function Home() {
  return (
    <div className='site-wrapper'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <main></main>

      <Footer />
    </div>
  );
}
